FROM node:20-slim
RUN apt-get update -y && apt-get install -y openssl ca-certificates libbrotli1 && rm -rf /var/lib/apt/lists/*
WORKDIR /app/backend
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx prisma generate
EXPOSE 3000
CMD ["sh", "-c", "npx prisma db push && npm run start:dev"]
